# Generated by Django 6.0.2 on 2026-02-17 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Regular User'), ('owner', 'Property Owner')], default='user', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=4, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=255, null=True)),
                ('identity_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('professional_status', models.CharField(blank=True, max_length=50, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_units', models.IntegerField(default=1)),
                ('avg_size_sqft', models.IntegerField(blank=True, null=True)),
                ('target_audience', models.JSONField(default=list)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_details', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Present', 'Present'), ('Permanent', 'Permanent')], max_length=10)),
                ('country', models.CharField(default='Bangladesh', max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('police_station', models.CharField(max_length=50)),
                ('area_name', models.CharField(max_length=100)),
                ('ward_no', models.CharField(max_length=20)),
                ('house_no', models.CharField(max_length=50)),
                ('floor_apt', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profile')),
            ],
        ),
    ]
