# Generated by Django 6.0.2 on 2026-02-24 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRadarAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('max_budget', models.IntegerField()),
                ('min_beds', models.CharField(max_length=20)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('frequency', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radars', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RadarNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('icon', models.CharField(default='fa-wand-magic-sparkles', max_length=50)),
                ('link', models.CharField(default='#', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_notifications', to='accounts.profile')),
            ],
        ),
    ]
