# Generated by Django 6.0.2 on 2026-02-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airadaralert',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
