# Generated by Django 6.0.2 on 2026-02-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dist_to_hospital_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='dist_to_station_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_hospital',
            field=models.CharField(default='General Hospital', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_station',
            field=models.CharField(default='Bus Stop', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='population_density_band',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='walkability_score',
            field=models.IntegerField(default=50),
        ),
    ]
