# Generated by Django 6.0.2 on 2026-02-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_chatconversation_chatmessage_delete_propertymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='last_email_sent_to_buyer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_email_sent_to_owner',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
